apiVersion: v1
kind: Service
metadata:
  name: communitynpservice-srv
spec:
  type: NodePort
  selector:
    app: communityservice
  ports:
    - name: communityservice
      protocol: TCP
      port: 80
      targetPort: 7000