apiVersion: apps/v1
kind: Deployment
metadata:
  name: community-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: communityservice
  template:
    metadata:
      labels:
        app: communityservice
    spec:
      containers:
        - name: communityservice
          image: hylissang/communityservice:latest