apiVersion: v1
kind: Service
metadata:
  name: docnpservice-srv
spec:
  type: NodePort
  selector:
    app: docservice
  ports:
    - name: docservice
      protocol: TCP
      port: 80
      targetPort: 6000