apiVersion: v1
kind: Service
metadata:
  name: knowbasenpservice-srv
spec:
  type: NodePort
  selector:
    app: knowbaseservice
  ports:
    - name: knowbaseservice
      protocol: TCP
      port: 80
      targetPort: 80